"""
materials.py — curated material library with rich phonological annotations.

Annotation types per word:
  stress    — stressed syllable marker (large dot above)
  weak      — weak/reduced form, label = phonetic reduction e.g. "wk /ə/"
  link      — linking, label = "linking →" or "← word"
  fall      — falling tone on this word ↘
  rise      — rising tone ↗
  fall_rise — fall-rise ↗↘
  nuclear   — nuclear stress (★, most prominent syllable in phrase)
  pause     — silence/pause marker (|), attach to preceding word

Each segment also has:
  pauses: list of word indices AFTER which a pause occurs
  intonation: "fall" | "rise" | "fall_rise" (sentence-final contour)
"""

import re

TAGS = {
    "stress":     {"label": "Stress Pattern", "zh": "重音模式",
                   "color": "#92400E", "bg": "#FFFBEB", "border": "#FDE68A"},
    "link":       {"label": "Linking",        "zh": "连读",
                   "color": "#1D4ED8", "bg": "#DBEAFE", "border": "#93C5FD"},
    "weak":       {"label": "Weak Form",      "zh": "弱读",
                   "color": "#5B21B6", "bg": "#EDE9FE", "border": "#C4B5FD"},
    "intonation": {"label": "Intonation",     "zh": "语调",
                   "color": "#065F46", "bg": "#ECFDF5", "border": "#6EE7B7"},
    "rhythm":     {"label": "Rhythm",         "zh": "节奏",
                   "color": "#9D174D", "bg": "#FCE7F3", "border": "#F9A8D4"},
    "omission":   {"label": "Omission",       "zh": "漏读",
                   "color": "#374151", "bg": "#F3F4F6", "border": "#D1D5DB"},
    "insertion":  {"label": "Insertion",      "zh": "多读",
                   "color": "#374151", "bg": "#F3F4F6", "border": "#D1D5DB"},
}


def _seg(idx, text, start, end, words, cue_en, cue_zh, intonation="fall", pauses=None):
    """
    words: list of dicts {w, anns:[]}
      ann types: stress | weak(label) | link(label) | fall | rise | fall_rise | nuclear | pause
    intonation: sentence-final contour — fall | rise | fall_rise
    pauses: list of word indices after which a pause mark appears
    """
    return {
        "idx":         idx,
        "text":        text,
        "ts":          {"start": start, "end": end},
        "words":       words,
        "cue_en":      cue_en,
        "cue_zh":      cue_zh,
        "intonation":  intonation,
        "pauses":      pauses or [],
        # legacy flat annotations kept for backward compat
        "annotations": _flatten_anns(words),
    }


def _flatten_anns(words):
    out = []
    for wd in words:
        for a in wd.get("anns", []):
            t = a["type"]
            tag_key = t if t in TAGS else "stress"
            out.append({
                "word":  wd["w"],
                "type":  tag_key,
                "label": a.get("label", TAGS.get(tag_key, {}).get("label", t)),
                "zh":    TAGS.get(tag_key, {}).get("zh", ""),
            })
    return out


def _w(word, *anns):
    """Word with annotations. Each ann is a dict {type, label?}"""
    return {"w": word, "anns": list(anns)}


def _stress():    return {"type": "stress"}
def _nuclear():   return {"type": "nuclear"}
def _fall():      return {"type": "fall"}
def _rise():      return {"type": "rise"}
def _fall_rise(): return {"type": "fall_rise"}
def _weak(label): return {"type": "weak", "label": label}
def _link(label): return {"type": "link", "label": label}


MUSIC_PRODIGY = {
    "id":           "music_prodigy",
    "title":        "Music Prodigy: Alma Deutscher",
    "difficulty":   "intermediate",
    "duration_sec": 105,
    "keywords":     ["prodigy", "talent", "practice", "music", "skills"],
    "audio_path":   "audio/music_prodigy.mp3",
    "segments": [

        _seg(0,
            "Prodigies are people with excellent skills in areas such as art or music.",
            0.5, 7.2,
            [
                _w("Prodigies",  _stress()),
                _w("are",        _weak("/ə/")),
                _w("people",     _stress()),
                _w("with",       _weak("/wɪ/")),
                _w("excellent",  _stress(), _nuclear()),
                _w("skills",     _link("linking →")),
                _w("in",         _weak("/ɪn/")),
                _w("areas",      _link("linking →")),
                _w("such",       _link("← such")),
                _w("as",         _weak("/əz/")),
                _w("art",        _stress()),
                _w("or",         _weak("/ə/")),
                _w("music",      _stress(), _fall()),
            ],
            "Listen for: 'excellent' carries the nuclear stress — the most prominent word. "
            "'areas such' links across the boundary. 'are', 'with', 'as', 'or' all reduce.",
            "注意：excellent 是核心重音词。areas such 发生连读。are、with、as、or 全部弱化。",
            intonation="fall",
        ),

        _seg(1,
            "Very often, they are experts even before they become teenagers.",
            7.2, 13.8,
            [
                _w("Very",       _stress()),
                _w("often,",     _stress()),
                _w("they",       _weak("/ðə/")),
                _w("are",        _weak("/ə/")),
                _w("experts",    _stress(), _link("linking →")),
                _w("even",       _link("← even")),
                _w("before",     _stress()),
                _w("they",       _weak("/ðə/")),
                _w("become",     _link("linking →")),
                _w("teenagers",  _nuclear(), _fall()),
            ],
            "Listen for: 'experts even' and 'become teenagers' both link. "
            "'are' reduces to a schwa — barely audible.",
            "注意：experts even 和 become teenagers 都连读。are 弱化为 /ə/，几乎听不见。",
            intonation="fall",
            pauses=[1],
        ),

        _seg(2,
            "Fourteen-year-old Alma Deutscher is a music prodigy.",
            13.8, 21.0,
            [
                _w("Fourteen-year-old", _stress()),
                _w("Alma",       _stress()),
                _w("Deutscher",  _stress()),
                _w("is",         _weak("/ɪz/")),
                _w("a",          _weak("/ə/")),
                _w("music",      _stress()),
                _w("prodigy",    _nuclear(), _fall()),
            ],
            "Listen for: four content words carry stress — Fourteen, Alma, Deutscher, prodigy. "
            "'is' and 'a' almost disappear.",
            "注意：四个实词承载重音。is 和 a 几乎消失。",
            intonation="fall",
        ),

        _seg(3,
            "She took up piano lessons when she was only two.",
            21.0, 26.8,
            [
                _w("She",        _weak("/ʃə/")),
                _w("took",       _link("linking →")),
                _w("up",         _link("← up"), _stress()),
                _w("piano",      _stress()),
                _w("lessons",    _stress()),
                _w("when",       _weak("/wən/")),
                _w("she",        _weak("/ʃə/")),
                _w("was",        _weak("/wəz/")),
                _w("only",       _stress()),
                _w("two",        _nuclear(), _fall()),
            ],
            "Listen for: 'took up' links — the /k/ blends into /ʌ/. "
            "'when', 'she', 'was' all reduce significantly.",
            "注意：took up 连读——/k/ 与 /ʌ/ 融合。when、she、was 都大幅弱化。",
            intonation="fall",
        ),

        _seg(4,
            "On her third birthday, she got a violin as a birthday gift.",
            26.8, 33.5,
            [
                _w("On",         _weak("/ɒn/")),
                _w("her",        _weak("/ə/")),
                _w("third",      _stress()),
                _w("birthday,",  _stress()),
                _w("she",        _weak("/ʃə/")),
                _w("got",        _stress()),
                _w("a",          _weak("/ə/")),
                _w("violin",     _stress()),
                _w("as",         _weak("/əz/")),
                _w("a",          _weak("/ə/")),
                _w("birthday",   _stress()),
                _w("gift",       _nuclear(), _fall()),
            ],
            "Listen for: 'violin' stresses the last syllable (vi-o-LIN). "
            "The sentence ends with a definitive falling tone on 'gift'.",
            "注意：violin 重音罕见地落在最后一个音节（vi-o-LIN）。句末 gift 有明确的降调。",
            intonation="fall",
            pauses=[3],
        ),

        _seg(5,
            "After she tried to play it for a few days, her parents found her a teacher.",
            33.5, 41.2,
            [
                _w("After",      _stress()),
                _w("she",        _weak("/ʃə/")),
                _w("tried",      _link("linking →")),
                _w("to",         _weak("/tə/")),
                _w("play",       _stress()),
                _w("it",         _weak("/ɪt/")),
                _w("for",        _weak("/fə/")),
                _w("a",          _weak("/ə/")),
                _w("few",        _stress()),
                _w("days,",      _stress()),
                _w("her",        _weak("/ə/")),
                _w("parents",    _stress()),
                _w("found",      _link("linking →")),
                _w("her",        _link("← her")),
                _w("a",          _weak("/ə/")),
                _w("teacher",    _nuclear(), _fall()),
            ],
            "Listen for: 'tried to' — 'to' reduces to /tə/. "
            "'found her' links. 'for a few' has three weak forms in a row.",
            "注意：tried to 中 to 弱化为 /tə/。found her 连读。for a few 连续三个弱读。",
            intonation="fall",
            pauses=[9],
        ),

        _seg(6,
            "When she was six, she wrote her first piece of music.",
            41.2, 47.0,
            [
                _w("When",       _weak("/wən/")),
                _w("she",        _weak("/ʃə/")),
                _w("was",        _weak("/wəz/")),
                _w("six,",       _stress()),
                _w("she",        _weak("/ʃə/")),
                _w("wrote",      _stress()),
                _w("her",        _weak("/ə/")),
                _w("first",      _stress()),
                _w("piece",      _link("linking →")),
                _w("of",         _weak("/əv/")),
                _w("music",      _nuclear(), _fall()),
            ],
            "Listen for: 'piece of' links — /s/ blends into 'of'. "
            "'when', 'she', 'was', 'her', 'of' all reduce.",
            "注意：piece of 连读——/s/ 与 of 融合。when、she、was、her、of 全部弱化。",
            intonation="fall",
            pauses=[3],
        ),

        _seg(7,
            "Now she performs at concerts around the world.",
            47.0, 52.5,
            [
                _w("Now",        _stress()),
                _w("she",        _weak("/ʃə/")),
                _w("performs",   _stress()),
                _w("at",         _weak("/ət/")),
                _w("concerts",   _stress()),
                _w("around",     _link("linking →")),
                _w("the",        _weak("/ðə/")),
                _w("world",      _nuclear(), _fall()),
            ],
            "Listen for: 'performs' stresses the second syllable (per-FORMS). "
            "'concerts' stresses the first (CON-certs). Sentence ends with a strong falling tone.",
            "注意：performs 重音在第二音节（per-FORMS）。concerts 重音在第一音节（CON-certs）。句末强降调。",
            intonation="fall",
        ),

    ],
}

# New materials to append to materials.py
# Each segment carefully selected for phonological richness and natural length

# ─────────────────────────────────────────────
# Easy 1 — Language Lab (complete)
# ─────────────────────────────────────────────
LANGUAGE_LAB = {
    "id":           "language_lab",
    "title":        "At the Language Lab",
    "difficulty":   "beginner",
    "duration_sec": 45,
    "keywords":     ["language lab", "videos", "Spanish", "reserve", "sign in"],
    "audio_path":   "audio/Easy1.mp3",
    "segments": [
        _seg(0,
            "Hi, I'm not sure, but is this the Carter Language Lab?",
            0.0, 4.0,
            [_w("Hi,",_stress()),_w("I'm",_weak("/aɪm/")),_w("not",_stress()),
             _w("sure,",_nuclear(),_rise()),_w("but",_stress()),_w("is",_weak("/ɪz/")),
             _w("this",_weak("/ðɪs/")),_w("the",_weak("/ðə/")),_w("Carter",_stress()),
             _w("Language",_stress()),_w("Lab",_nuclear(),_rise())],
            "Rising tone — yes/no question. 'I'm', 'is', 'this', 'the' all reduce.",
            "句末升调（一般疑问句）。I'm、is、this、the 全部弱化。",
            intonation="rise",
        ),
        _seg(1,
            "Yes, it is. How can I help you?",
            4.0, 6.5,
            [_w("Yes,",_stress()),_w("it",_weak("/ɪt/")),_w("is.",_nuclear(),_fall()),
             _w("How",_stress()),_w("can",_weak("/kən/")),_w("I",_weak("/aɪ/")),
             _w("help",_stress()),_w("you",_nuclear(),_rise())],
            "Fall on 'is' — confirming. Rise on 'you' — offer/question.",
            "is 处降调（确认）。you 处升调（提问/邀请）。",
            intonation="rise",
            pauses=[2],
        ),
        _seg(2,
            "I'm taking first-year Spanish this semester.",
            6.5, 9.5,
            [_w("I'm",_weak("/aɪm/")),_w("taking",_stress()),_w("first-year",_stress()),
             _w("Spanish",_stress()),_w("this",_weak("/ðɪs/")),_w("semester",_nuclear(),_fall())],
            "'I'm' reduces. Strong stress on 'first-year Spanish'.",
            "I'm 弱化。first-year Spanish 重音突出。",
            intonation="fall",
        ),
        _seg(3,
            "Our professor says we need to come here to view a series of videos.",
            9.5, 14.5,
            [_w("Our",_weak("/ə/")),_w("professor",_stress()),_w("says",_stress()),
             _w("we",_weak("/wɪ/")),_w("need",_stress()),_w("to",_weak("/tə/")),
             _w("come",_link("linking →")),_w("here",_stress()),_w("to",_weak("/tə/")),
             _w("view",_stress()),_w("a",_weak("/ə/")),_w("series",_stress()),
             _w("of",_weak("/əv/")),_w("videos",_nuclear(),_fall())],
            "'come here' links. Both 'to' reduce. 'Our', 'we', 'a', 'of' reduce.",
            "come here 连读。两个 to 弱化。Our、we、a、of 全部弱化。",
            intonation="fall",
        ),
        _seg(4,
            "I think it's called Spanish working on your accent?",
            14.5, 18.5,
            [_w("I",_weak("/aɪ/")),_w("think",_stress()),_w("it's",_weak("/ɪts/")),
             _w("called",_stress()),_w("Spanish",_stress()),_w("working",_stress()),
             _w("on",_weak("/ɒn/")),_w("your",_weak("/jə/")),_w("accent",_nuclear(),_rise())],
            "Rising tone — uncertain, checking. 'it's', 'on', 'your' reduce.",
            "句末升调（不确定，在确认）。it's、on、your 弱化。",
            intonation="rise",
        ),
        _seg(5,
            "Yes, we have that. They're on the wall behind you.",
            18.5, 22.5,
            [_w("Yes,",_stress()),_w("we",_weak("/wɪ/")),_w("have",_stress()),
             _w("that.",_nuclear(),_fall()),_w("They're",_weak("/ðeə/")),
             _w("on",_weak("/ɒn/")),_w("the",_weak("/ðə/")),_w("wall",_stress()),
             _w("behind",_stress()),_w("you",_nuclear(),_fall())],
            "Two tone units — fall on 'that', fall on 'you'. 'They're', 'on', 'the' reduce.",
            "两个语调单位，各自降调。They're、on、the 全部弱化。",
            intonation="fall",
            pauses=[3],
        ),
        _seg(6,
            "Okay, so I can just take, can I just take the whole series home?",
            22.5, 27.5,
            [_w("Okay,",_fall_rise()),_w("so",_stress()),_w("I",_weak("/aɪ/")),
             _w("can",_weak("/kən/")),_w("just",_stress()),_w("take,",_nuclear(),_rise()),
             _w("can",_weak("/kən/")),_w("I",_weak("/aɪ/")),_w("just",_stress()),
             _w("take",_stress()),_w("the",_weak("/ðə/")),_w("whole",_stress()),
             _w("series",_stress()),_w("home",_nuclear(),_rise())],
            "Self-correction mid-sentence. 'can' reduces twice. Rising — yes/no question.",
            "句中自我纠正。can 两次弱化。句末升调（一般疑问句）。",
            intonation="rise",
            pauses=[5],
        ),
        _seg(7,
            "I think there are three of them.",
            27.5, 30.0,
            [_w("I",_weak("/aɪ/")),_w("think",_stress()),_w("there",_weak("/ðə/")),
             _w("are",_weak("/ə/")),_w("three",_stress()),_w("of",_weak("/əv/")),
             _w("them",_nuclear(),_fall())],
            "'there are' both reduce. 'of them' reduces. Falling — stating a fact.",
            "there are 都弱化。of them 弱化。降调（陈述事实）。",
            intonation="fall",
        ),
        _seg(8,
            "I guess you haven't been here before.",
            30.0, 33.0,
            [_w("I",_weak("/aɪ/")),_w("guess",_stress()),_w("you",_weak("/jə/")),
             _w("haven't",_stress()),_w("been",_weak("/bɪn/")),_w("here",_stress()),
             _w("before",_nuclear(),_fall())],
            "'I guess' — hedging. 'you', 'been' reduce. Fall on 'before'.",
            "I guess 是缓和语气。you、been 弱化。before 处降调。",
            intonation="fall",
        ),
        _seg(9,
            "Okay, well you have to watch the videos here.",
            33.0, 36.5,
            [_w("Okay,",_fall_rise()),_w("well",_fall_rise()),_w("you",_weak("/jə/")),
             _w("have",_stress()),_w("to",_weak("/tə/")),_w("watch",_stress()),
             _w("the",_weak("/ðə/")),_w("videos",_stress()),_w("here",_nuclear(),_fall())],
            "'have to' → /hæftə/. 'Okay', 'well' — fall-rise discourse markers.",
            "have to 读成 /hæftə/。Okay 和 well 都是 fall-rise 话语标记。",
            intonation="fall",
        ),
        _seg(10,
            "You need to sign in to reserve an open room and sign out the video you need.",
            36.5, 43.0,
            [_w("You",_weak("/jə/")),_w("need",_stress()),_w("to",_weak("/tə/")),
             _w("sign",_stress()),_w("in",_weak("/ɪn/")),_w("to",_weak("/tə/")),
             _w("reserve",_stress()),_w("an",_link("linking →")),
             _w("open",_link("← open"),_stress()),_w("room",_stress()),
             _w("and",_weak("/ən/")),_w("sign",_stress()),_w("out",_stress()),
             _w("the",_weak("/ðə/")),_w("video",_stress()),_w("you",_weak("/jə/")),
             _w("need",_nuclear(),_fall())],
            "'reserve an open' links. 'and' → /ən/. Multiple weak forms.",
            "reserve an open 连读。and 弱化为 /ən/。全句多处弱化。",
            intonation="fall",
        ),
        _seg(11,
            "Just start with the first one in the series. Each video is half an hour long.",
            43.0, 49.0,
            [_w("Just",_stress()),_w("start",_link("linking →")),_w("with",_weak("/wɪ/")),
             _w("the",_weak("/ðə/")),_w("first",_stress()),_w("one",_link("linking →")),
             _w("in",_weak("/ɪn/")),_w("the",_weak("/ðə/")),_w("series.",_nuclear(),_fall()),
             _w("Each",_stress()),_w("video",_stress()),_w("is",_weak("/ɪz/")),
             _w("half",_stress()),_w("an",_link("linking →")),
             _w("hour",_link("← hour"),_nuclear()),_w("long",_fall())],
            "'start with' links. 'one in' links. 'half an hour' — three-word linking chain.",
            "start with 连读，one in 连读，half an hour 三词连续连读。",
            intonation="fall",
            pauses=[8],
        ),
    ],
}

# ─────────────────────────────────────────────
# Easy 2 — Library (complete)
# ─────────────────────────────────────────────
LIBRARY = {
    "id":           "library",
    "title":        "Finding Books at the Library",
    "difficulty":   "beginner",
    "duration_sec": 55,
    "keywords":     ["library", "computer", "New Zealand", "volcano", "search"],
    "audio_path":   "audio/easy2.mp3",
    "segments": [
        _seg(0,
            "Hi, can I help you?",
            0.0, 2.5,
            [_w("Hi,",_stress()),_w("can",_weak("/kən/")),_w("I",_weak("/aɪ/")),
             _w("help",_stress()),_w("you",_nuclear(),_rise())],
            "Rising — offer/question. 'can', 'I' reduce.",
            "升调（提问/提供帮助）。can、I 弱化。",
            intonation="rise",
        ),
        _seg(1,
            "Where do I go, besides the computers, to look for books on New Zealand?",
            2.5, 8.0,
            [_w("Where",_stress()),_w("do",_weak("/də/")),_w("I",_weak("/aɪ/")),
             _w("go,",_stress()),_w("besides",_stress()),_w("the",_weak("/ðə/")),
             _w("computers,",_nuclear(),_rise()),_w("to",_weak("/tə/")),
             _w("look",_stress()),_w("for",_weak("/fə/")),_w("books",_stress()),
             _w("on",_weak("/ɒn/")),_w("New",_stress()),_w("Zealand",_nuclear(),_fall())],
            "Rise on 'computers' — parenthetical. Fall on 'Zealand'. 'do', 'to', 'for', 'on' reduce.",
            "computers 处升调（插入语）。Zealand 处降调。do、to、for、on 全部弱化。",
            intonation="fall",
            pauses=[3, 6],
        ),
        _seg(2,
            "Okay, you mean you don't want to use the computer?",
            8.0, 12.0,
            [_w("Okay,",_fall_rise()),_w("you",_weak("/jə/")),_w("mean",_stress()),
             _w("you",_weak("/jə/")),_w("don't",_stress()),_w("want",_stress()),
             _w("to",_weak("/tə/")),_w("use",_stress()),_w("the",_weak("/ðə/")),
             _w("computer",_nuclear(),_rise())],
            "'Okay' — fall-rise, processing. Rising — clarifying question. Both 'you' reduce.",
            "Okay 使用 fall-rise（思考中）。句末升调（确认问句）。两个 you 都弱化。",
            intonation="rise",
        ),
        _seg(3,
            "Well, I haven't had any luck on the computers here.",
            12.0, 16.0,
            [_w("Well,",_fall_rise()),_w("I",_weak("/aɪ/")),_w("haven't",_stress()),
             _w("had",_stress()),_w("any",_stress()),_w("luck",_stress()),
             _w("on",_weak("/ɒn/")),_w("the",_weak("/ðə/")),_w("computers",_stress()),
             _w("here",_nuclear(),_fall())],
            "'Well' — fall-rise, mild complaint. 'on', 'the' reduce.",
            "Well 使用 fall-rise（轻微抱怨）。on、the 弱化。",
            intonation="fall",
        ),
        _seg(4,
            "I mean, the reason I'm asking is you pretty much have to go to the computer to find out where a book is.",
            16.0, 23.5,
            [_w("I",_stress()),_w("mean,",_fall_rise()),_w("the",_weak("/ðə/")),
             _w("reason",_stress()),_w("I'm",_weak("/aɪm/")),_w("asking",_stress()),
             _w("is",_weak("/ɪz/")),_w("you",_weak("/jə/")),_w("pretty",_stress()),
             _w("much",_stress()),_w("have",_stress()),_w("to",_weak("/tə/")),
             _w("go",_stress()),_w("to",_weak("/tə/")),_w("the",_weak("/ðə/")),
             _w("computer",_stress()),_w("to",_weak("/tə/")),_w("find",_link("linking →")),
             _w("out",_link("← out"),_stress()),_w("where",_stress()),
             _w("a",_weak("/ə/")),_w("book",_stress()),_w("is",_nuclear(),_fall())],
            "'I mean' — fall-rise hedging. 'find out' links. 'have to' → /hæftə/.",
            "I mean 使用 fall-rise。find out 连读。have to 读成 /hæftə/。",
            intonation="fall",
            pauses=[1],
        ),
        _seg(5,
            "But I can help you find it on the computer, if you like.",
            23.5, 27.5,
            [_w("But",_stress()),_w("I",_weak("/aɪ/")),_w("can",_weak("/kən/")),
             _w("help",_stress()),_w("you",_weak("/jə/")),_w("find",_link("linking →")),
             _w("it",_link("← it"),_weak("/ɪt/")),_w("on",_weak("/ɒn/")),
             _w("the",_weak("/ðə/")),_w("computer,",_nuclear(),_rise()),
             _w("if",_weak("/ɪf/")),_w("you",_weak("/jə/")),_w("like",_nuclear(),_fall())],
            "'find it' links. Rise on 'computer' — condition coming. 'can', 'you', 'if' reduce.",
            "find it 连读。computer 处升调（后有条件从句）。can、you、if 弱化。",
            intonation="fall",
            pauses=[9],
        ),
        _seg(6,
            "That would be great. I just spent half an hour and I couldn't find anything.",
            27.5, 33.5,
            [_w("That",_stress()),_w("would",_weak("/wəd/")),_w("be",_weak("/bɪ/")),
             _w("great.",_nuclear(),_fall()),_w("I",_stress()),_w("just",_stress()),
             _w("spent",_link("linking →")),_w("half",_link("← half"),_stress()),
             _w("an",_link("linking →")),_w("hour",_link("← hour"),_stress()),
             _w("and",_weak("/ən/")),_w("I",_weak("/aɪ/")),_w("couldn't",_stress()),
             _w("find",_link("linking →")),_w("anything",_nuclear(),_fall())],
            "'would be' both reduce. 'spent half an hour' — three-word linking chain.",
            "would be 都弱化。spent half an hour 三词连续连读。",
            intonation="fall",
            pauses=[3],
        ),
        _seg(7,
            "I know how you feel. When I first started working here, I couldn't find anything either.",
            33.5, 40.0,
            [_w("I",_weak("/aɪ/")),_w("know",_stress()),_w("how",_stress()),
             _w("you",_weak("/jə/")),_w("feel.",_nuclear(),_fall()),
             _w("When",_weak("/wən/")),_w("I",_weak("/aɪ/")),_w("first",_stress()),
             _w("started",_stress()),_w("working",_stress()),_w("here,",_nuclear(),_rise()),
             _w("I",_weak("/aɪ/")),_w("couldn't",_stress()),_w("find",_link("linking →")),
             _w("anything",_stress()),_w("either",_nuclear(),_fall())],
            "Rise on 'here' — first clause. Fall on 'either'. 'find anything' links.",
            "here 处升调（从句结束）。either 处降调。find anything 连读。",
            intonation="fall",
            pauses=[4, 10],
        ),
        _seg(8,
            "So you're looking for information on New Zealand, is that right?",
            40.0, 45.0,
            [_w("So",_stress()),_w("you're",_weak("/jə/")),_w("looking",_stress()),
             _w("for",_weak("/fə/")),_w("information",_stress()),_w("on",_weak("/ɒn/")),
             _w("New",_stress()),_w("Zealand,",_nuclear(),_rise()),
             _w("is",_weak("/ɪz/")),_w("that",_weak("/ðət/")),_w("right",_nuclear(),_rise())],
            "Two rises — 'Zealand' and 'right'. Confirmation question. Multiple weak forms.",
            "两处升调（Zealand 和 right）。确认问句句型。多处弱化。",
            intonation="rise",
            pauses=[7],
        ),
        _seg(9,
            "Is it like travel information that you're looking for?",
            45.0, 49.0,
            [_w("Is",_weak("/ɪz/")),_w("it",_weak("/ɪt/")),_w("like",_stress()),
             _w("travel",_stress()),_w("information",_stress()),_w("that",_weak("/ðət/")),
             _w("you're",_weak("/jə/")),_w("looking",_stress()),_w("for",_nuclear(),_rise())],
            "Rising — yes/no question. 'Is it' → /ɪzɪt/. 'that', 'you're' reduce.",
            "句末升调。Is it 连读为 /ɪzɪt/。that、you're 弱化。",
            intonation="rise",
        ),
        _seg(10,
            "No, actually what I'm looking for is information on a volcano in New Zealand.",
            49.0, 55.0,
            [_w("No,",_stress(),_fall()),_w("actually",_stress()),_w("what",_stress()),
             _w("I'm",_weak("/aɪm/")),_w("looking",_stress()),_w("for",_weak("/fə/")),
             _w("is",_weak("/ɪz/")),_w("information",_stress()),_w("on",_weak("/ɒn/")),
             _w("a",_weak("/ə/")),_w("volcano",_nuclear()),_w("in",_weak("/ɪn/")),
             _w("New",_stress()),_w("Zealand",_nuclear(),_fall())],
            "'No' — own falling tone, contrast. Heavy stress on 'volcano' — new key info.",
            "No 独立降调（转折对比）。volcano 是新信息，核心重音最突出。",
            intonation="fall",
            pauses=[0],
        ),
    ],
}

# ─────────────────────────────────────────────
# Medium 1 — Choir Noise (complete)
# ─────────────────────────────────────────────
CHOIR_NOISE = {
    "id":           "choir_noise",
    "title":        "The Choir's Noise Problem",
    "difficulty":   "intermediate",
    "duration_sec": 65,
    "keywords":     ["choir", "rehearsal", "construction", "noise", "auditorium"],
    "audio_path":   "audio/medium1.mp3",
    "segments": [
        _seg(0,
            "Hi, I'm Melanie, the one who's been calling.",
            0.0, 4.0,
            [_w("Hi,",_stress()),_w("I'm",_weak("/aɪm/")),_w("Melanie,",_nuclear(),_rise()),
             _w("the",_weak("/ðə/")),_w("one",_stress()),_w("who's",_weak("/huːz/")),
             _w("been",_weak("/bɪn/")),_w("calling",_nuclear(),_fall())],
            "Rise on 'Melanie' — more coming. 'who's been' reduce. 'I'm', 'the' reduce.",
            "Melanie 处升调（还有补充）。who's been 都弱化。I'm、the 弱化。",
            intonation="fall",
            pauses=[2],
        ),
        _seg(1,
            "From the singing group, right? From the choir.",
            4.0, 7.5,
            [_w("From",_weak("/frəm/")),_w("the",_weak("/ðə/")),_w("singing",_stress()),
             _w("group,",_nuclear(),_rise()),_w("right",_nuclear(),_rise()),
             _w("From",_weak("/frəm/")),_w("the",_weak("/ðə/")),_w("choir",_nuclear(),_fall())],
            "Two rises — guessing, checking. Fall on 'choir' — correction/clarification.",
            "两处升调（猜测，在确认）。choir 处降调（纠正说法）。",
            intonation="fall",
            pauses=[3],
        ),
        _seg(2,
            "It's nice to finally meet you in person.",
            7.5, 10.5,
            [_w("It's",_weak("/ɪts/")),_w("nice",_stress()),_w("to",_weak("/tə/")),
             _w("finally",_stress()),_w("meet",_link("linking →")),
             _w("you",_link("← you"),_weak("/jə/")),_w("in",_weak("/ɪn/")),
             _w("person",_nuclear(),_fall())],
            "'meet you' links — /t/ blends into /j/ → /tʃ/. 'It's', 'to', 'you', 'in' reduce.",
            "meet you 连读，/t/ 与 /j/ 融合为 /tʃ/。It's、to、you、in 全部弱化。",
            intonation="fall",
        ),
        _seg(3,
            "Like I explained on the phone, we've always had our rehearsals in the Lincoln Auditorium, every day at three o'clock, and it's always worked just great.",
            10.5, 20.0,
            [_w("Like",_stress()),_w("I",_weak("/aɪ/")),_w("explained",_link("linking →")),
             _w("on",_link("← on"),_weak("/ɒn/")),_w("the",_weak("/ðə/")),
             _w("phone,",_nuclear(),_rise()),_w("we've",_weak("/wɪv/")),
             _w("always",_stress()),_w("had",_stress()),_w("our",_weak("/ə/")),
             _w("rehearsals",_stress()),_w("in",_weak("/ɪn/")),_w("the",_weak("/ðə/")),
             _w("Lincoln",_stress()),_w("Auditorium,",_nuclear(),_rise()),
             _w("every",_stress()),_w("day",_stress()),_w("at",_weak("/ət/")),
             _w("three",_stress()),_w("o'clock,",_nuclear(),_rise()),
             _w("and",_weak("/ən/")),_w("it's",_weak("/ɪts/")),_w("always",_stress()),
             _w("worked",_stress()),_w("just",_stress()),_w("great",_nuclear(),_fall())],
            "Three listing rises: 'phone', 'Auditorium', 'o'clock'. Final fall 'great'. 'explained on' links.",
            "三处列举升调（phone/Auditorium/o'clock）。great 最终降调。explained on 连读。",
            intonation="fall",
            pauses=[5, 14, 19],
        ),
        _seg(4,
            "But the past few weeks, with the noise, it's been a total nightmare, since construction started next door on the Science Hall.",
            20.0, 29.0,
            [_w("But",_stress()),_w("the",_weak("/ðə/")),_w("past",_stress()),
             _w("few",_stress()),_w("weeks,",_nuclear(),_rise()),_w("with",_weak("/wɪ/")),
             _w("the",_weak("/ðə/")),_w("noise,",_nuclear(),_rise()),_w("it's",_weak("/ɪts/")),
             _w("been",_weak("/bɪn/")),_w("a",_weak("/ə/")),_w("total",_stress()),
             _w("nightmare,",_nuclear(),_fall()),_w("since",_stress()),
             _w("construction",_stress()),_w("started",_stress()),_w("next",_stress()),
             _w("door",_link("linking →")),_w("on",_link("← on"),_weak("/ɒn/")),
             _w("the",_weak("/ðə/")),_w("Science",_stress()),_w("Hall",_nuclear(),_fall())],
            "Two parenthetical rises: 'weeks', 'noise'. Heavy fall 'nightmare'. 'door on' links.",
            "两处插入语升调（weeks/noise）。nightmare 情绪化降调。door on 连读。",
            intonation="fall",
            pauses=[4, 7, 12],
        ),
        _seg(5,
            "Oh, that's right, they're building that addition for new laboratories.",
            29.0, 34.5,
            [_w("Oh,",_fall_rise()),_w("that's",_stress()),_w("right,",_nuclear(),_fall()),
             _w("they're",_weak("/ðeə/")),_w("building",_stress()),_w("that",_weak("/ðət/")),
             _w("addition",_stress()),_w("for",_weak("/fə/")),_w("new",_stress()),
             _w("laboratories",_nuclear(),_fall())],
            "'Oh' — fall-rise, remembering. 'that's right' — acknowledgement falls. 'for' reduces.",
            "Oh 使用 fall-rise（想起来了）。that's right 是确认降调。for 弱化。",
            intonation="fall",
            pauses=[2],
        ),
        _seg(6,
            "Anyway, ever since they started working on it, it's been so noisy we can barely hear ourselves think.",
            34.5, 42.5,
            [_w("Anyway,",_fall_rise()),_w("ever",_stress()),_w("since",_stress()),
             _w("they",_weak("/ðə/")),_w("started",_stress()),_w("working",_link("linking →")),
             _w("on",_link("← on"),_weak("/ɒn/")),_w("it,",_nuclear(),_rise()),
             _w("it's",_weak("/ɪts/")),_w("been",_weak("/bɪn/")),_w("so",_stress()),
             _w("noisy",_nuclear()),_w("we",_weak("/wɪ/")),_w("can",_weak("/kən/")),
             _w("barely",_stress()),_w("hear",_link("linking →")),
             _w("ourselves",_link("← ourselves"),_stress()),_w("think",_nuclear(),_fall())],
            "'Anyway' — fall-rise, topic shift. 'working on it' links. 'hear ourselves' links.",
            "Anyway 使用 fall-rise（转换话题）。working on it 连读。hear ourselves 连读。",
            intonation="fall",
            pauses=[7],
        ),
        _seg(7,
            "Let alone sing.",
            42.5, 44.5,
            [_w("Let",_stress()),_w("alone",_stress()),_w("sing",_nuclear(),_fall())],
            "Short emphatic tag — strong fall. Each word gets stress.",
            "简短强调补充，强烈降调。每个词都有重音。",
            intonation="fall",
        ),
        _seg(8,
            "Forget about singing! I mean, we keep the windows down and everything, but once those bulldozers get going, those machines are loud.",
            44.5, 54.0,
            [_w("Forget",_stress()),_w("about",_weak("/əbaʊt/")),_w("singing!",_nuclear(),_fall()),
             _w("I",_stress()),_w("mean,",_fall_rise()),_w("we",_weak("/wɪ/")),
             _w("keep",_stress()),_w("the",_weak("/ðə/")),_w("windows",_stress()),
             _w("down",_stress()),_w("and",_weak("/ən/")),_w("everything,",_nuclear(),_rise()),
             _w("but",_stress()),_w("once",_stress()),_w("those",_stress()),
             _w("bulldozers",_stress()),_w("get",_link("linking →")),
             _w("going,",_nuclear(),_rise()),_w("those",_stress()),_w("machines",_stress()),
             _w("are",_weak("/ə/")),_w("loud",_nuclear(),_fall())],
            "Emphatic fall on 'singing'. 'I mean' fall-rise. 'get going' links. 'are' → /ə/.",
            "singing 处强调降调。I mean 使用 fall-rise。get going 连读。are 弱化为 /ə/。",
            intonation="fall",
            pauses=[2, 11, 17],
        ),
        _seg(9,
            "We've already had to cut short two rehearsals, and we've got a concert in six weeks.",
            54.0, 61.0,
            [_w("We've",_weak("/wɪv/")),_w("already",_stress()),_w("had",_stress()),
             _w("to",_weak("/tə/")),_w("cut",_stress()),_w("short",_stress()),
             _w("two",_stress()),_w("rehearsals,",_nuclear(),_rise()),
             _w("and",_weak("/ən/")),_w("we've",_weak("/wɪv/")),_w("got",_stress()),
             _w("a",_weak("/ə/")),_w("concert",_stress()),_w("in",_weak("/ɪn/")),
             _w("six",_stress()),_w("weeks",_nuclear(),_fall())],
            "Rise on 'rehearsals' — urgency building. Final fall on 'weeks'.",
            "rehearsals 处升调（还有更多）。weeks 处降调突显紧迫感。",
            intonation="fall",
            pauses=[7],
        ),
    ],
}

# ─────────────────────────────────────────────
# Medium 2 — Jazz Band (complete)
# ─────────────────────────────────────────────
JAZZ_BAND = {
    "id":           "jazz_band",
    "title":        "Switching Shifts for Jazz Band",
    "difficulty":   "intermediate",
    "duration_sec": 60,
    "keywords":     ["dining hall", "shift", "jazz band", "audition", "schedule"],
    "audio_path":   "audio/medium2.mp3",
    "segments": [
        _seg(0,
            "Excuse me, Mrs. Hanson? My name's John, John Grant.",
            0.0, 5.0,
            [_w("Excuse",_stress()),_w("me,",_weak("/mɪ/")),_w("Mrs.",_stress()),
             _w("Hanson?",_nuclear(),_rise()),_w("My",_stress()),_w("name's",_stress()),
             _w("John,",_nuclear(),_rise()),_w("John",_stress()),_w("Grant",_nuclear(),_fall())],
            "Rise on 'Hanson' — calling attention. Rise on 'John' — adding surname.",
            "Hanson 处升调（呼唤对方）。John 处升调（补充姓名）。",
            intonation="fall",
            pauses=[3, 6],
        ),
        _seg(1,
            "I work as a waiter in the campus dining hall, in the faculty dining room.",
            5.0, 10.5,
            [_w("I",_weak("/aɪ/")),_w("work",_link("linking →")),
             _w("as",_link("← as"),_weak("/əz/")),_w("a",_weak("/ə/")),
             _w("waiter",_stress()),_w("in",_weak("/ɪn/")),_w("the",_weak("/ðə/")),
             _w("campus",_stress()),_w("dining",_stress()),_w("hall,",_nuclear(),_rise()),
             _w("in",_weak("/ɪn/")),_w("the",_weak("/ðə/")),_w("faculty",_stress()),
             _w("dining",_stress()),_w("room",_nuclear(),_fall())],
            "'work as' links. Rise on 'hall' — specifying further.",
            "work as 连读。hall 处升调（后面有补充说明）。",
            intonation="fall",
            pauses=[9],
        ),
        _seg(2,
            "What can I do for you, John?",
            10.5, 13.0,
            [_w("What",_stress()),_w("can",_weak("/kən/")),_w("I",_weak("/aɪ/")),
             _w("do",_stress()),_w("for",_weak("/fə/")),_w("you,",_weak("/jə/")),
             _w("John",_nuclear(),_fall())],
            "Fall on 'John' — friendly but businesslike. 'can', 'I', 'for', 'you' reduce.",
            "John 处降调（友好但正式）。can、I、for、you 全部弱化。",
            intonation="fall",
        ),
        _seg(3,
            "Well, I work weeknights, except for Friday. I was wondering if I could switch from working the dinner service to working at lunch.",
            13.0, 22.0,
            [_w("Well,",_fall_rise()),_w("I",_weak("/aɪ/")),_w("work",_stress()),
             _w("weeknights,",_nuclear(),_rise()),_w("except",_stress()),
             _w("for",_weak("/fə/")),_w("Friday.",_nuclear(),_fall()),
             _w("I",_weak("/aɪ/")),_w("was",_weak("/wəz/")),_w("wondering",_stress()),
             _w("if",_weak("/ɪf/")),_w("I",_weak("/aɪ/")),_w("could",_weak("/kəd/")),
             _w("switch",_stress()),_w("from",_weak("/frəm/")),_w("working",_stress()),
             _w("the",_weak("/ðə/")),_w("dinner",_stress()),_w("service",_nuclear(),_rise()),
             _w("to",_weak("/tə/")),_w("working",_stress()),_w("at",_weak("/ət/")),
             _w("lunch",_nuclear(),_fall())],
            "'I was wondering if' — polite request formula. Rise on 'weeknights', 'service' — contrast.",
            "I was wondering if 是礼貌请求公式，大量弱化。weeknights 和 service 各有升调。",
            intonation="fall",
            pauses=[3, 6, 18],
        ),
        _seg(4,
            "That's going to be a problem. I'm afraid we don't have any openings at lunchtime.",
            22.0, 29.0,
            [_w("That's",_stress()),_w("going",_stress()),_w("to",_weak("/tə/")),
             _w("be",_weak("/bɪ/")),_w("a",_weak("/ə/")),_w("problem.",_nuclear(),_fall()),
             _w("I'm",_weak("/aɪm/")),_w("afraid",_stress()),_w("we",_weak("/wɪ/")),
             _w("don't",_stress()),_w("have",_stress()),_w("any",_stress()),
             _w("openings",_nuclear()),_w("at",_weak("/ət/")),_w("lunchtime",_nuclear(),_fall())],
            "'going to' → /gənə/. 'I'm afraid' — softening formula.",
            "going to 弱化为 /gənə/。I'm afraid 是缓和公式。",
            intonation="fall",
            pauses=[5],
        ),
        _seg(5,
            "A lot of students want to work then, so it's really rare for us to have an open spot at that time of day.",
            29.0, 37.0,
            [_w("A",_weak("/ə/")),_w("lot",_stress()),_w("of",_weak("/əv/")),
             _w("students",_stress()),_w("want",_stress()),_w("to",_weak("/tə/")),
             _w("work",_stress()),_w("then,",_nuclear(),_rise()),_w("so",_weak("/sə/")),
             _w("it's",_weak("/ɪts/")),_w("really",_stress()),_w("rare",_stress()),
             _w("for",_weak("/fə/")),_w("us",_weak("/əs/")),_w("to",_weak("/tə/")),
             _w("have",_stress()),_w("an",_link("linking →")),
             _w("open",_link("← open"),_stress()),_w("spot",_nuclear()),
             _w("at",_weak("/ət/")),_w("that",_weak("/ðət/")),_w("time",_stress()),
             _w("of",_weak("/əv/")),_w("day",_nuclear(),_fall())],
            "Rise on 'then' — reason clause coming. 'an open' links. 'so', 'of' reduce.",
            "then 处升调（后面有原因）。an open 连读。so、of 弱化。",
            intonation="fall",
            pauses=[7],
        ),
        _seg(6,
            "Well, you see, I've joined this group, the University Jazz Band, and the band's practice time's right around dinnertime.",
            37.0, 45.0,
            [_w("Well,",_fall_rise()),_w("you",_weak("/jə/")),_w("see,",_fall_rise()),
             _w("I've",_stress()),_w("joined",_stress()),_w("this",_weak("/ðɪs/")),
             _w("group,",_nuclear(),_rise()),_w("the",_weak("/ðə/")),
             _w("University",_stress()),_w("Jazz",_stress()),_w("Band,",_nuclear(),_rise()),
             _w("and",_weak("/ən/")),_w("the",_weak("/ðə/")),_w("band's",_stress()),
             _w("practice",_stress()),_w("time's",_stress()),_w("right",_stress()),
             _w("around",_link("linking →")),_w("dinnertime",_nuclear(),_fall())],
            "'Well, you see' — double fall-rise, explanation coming. 'around dinnertime' links.",
            "Well, you see 双重 fall-rise（要解释了）。around dinnertime 连读。",
            intonation="fall",
            pauses=[2, 6],
        ),
        _seg(7,
            "You know, it's so hard to get into this group. I must have auditioned like ten times since I've been at the school.",
            45.0, 54.0,
            [_w("You",_weak("/jə/")),_w("know,",_fall_rise()),_w("it's",_weak("/ɪts/")),
             _w("so",_stress()),_w("hard",_stress()),_w("to",_weak("/tə/")),
             _w("get",_link("linking →")),_w("into",_link("← into"),_stress()),
             _w("this",_weak("/ðɪs/")),_w("group.",_nuclear(),_fall()),
             _w("I",_stress()),_w("must",_stress()),_w("have",_weak("/əv/")),
             _w("auditioned",_stress()),_w("like",_stress()),_w("ten",_stress()),
             _w("times",_stress()),_w("since",_stress()),_w("I've",_weak("/aɪv/")),
             _w("been",_weak("/bɪn/")),_w("at",_weak("/ət/")),_w("the",_weak("/ðə/")),
             _w("school",_nuclear(),_fall())],
            "'You know' — fall-rise. 'get into' links. 'must have' — 'have' → /əv/.",
            "You know 使用 fall-rise。get into 连读。must have 中 have 弱化为 /əv/。",
            intonation="fall",
            pauses=[1, 9],
        ),
        _seg(8,
            "So I was really hoping to have the dinner hour free so I can go to practice.",
            54.0, 60.5,
            [_w("So",_stress()),_w("I",_weak("/aɪ/")),_w("was",_weak("/wəz/")),
             _w("really",_stress()),_w("hoping",_stress()),_w("to",_weak("/tə/")),
             _w("have",_stress()),_w("the",_weak("/ðə/")),_w("dinner",_stress()),
             _w("hour",_stress()),_w("free",_nuclear(),_rise()),_w("so",_weak("/sə/")),
             _w("I",_weak("/aɪ/")),_w("can",_weak("/kən/")),_w("go",_stress()),
             _w("to",_weak("/tə/")),_w("practice",_nuclear(),_fall())],
            "Rise on 'free' — reason clause coming. Fall on 'practice'. 'so', 'can' reduce.",
            "free 处升调（后面有原因从句）。practice 处最终降调。so、can 弱化。",
            intonation="fall",
            pauses=[10],
        ),
        _seg(9,
            "Well, we do have other open times, like breakfast.",
            60.5, 65.5,
            [_w("Well,",_fall_rise()),_w("we",_weak("/wɪ/")),_w("do",_stress()),
             _w("have",_stress()),_w("other",_stress()),_w("open",_link("linking →")),
             _w("times,",_nuclear(),_rise()),_w("like",_stress()),
             _w("breakfast",_nuclear(),_fall())],
            "'Well' — fall-rise, compromise signal. 'do' — emphatic. 'open times' links.",
            "Well 使用 fall-rise（提出折中方案）。do 是对比强调。open times 连读。",
            intonation="fall",
            pauses=[6],
        ),
    ],
}

# ─────────────────────────────────────────────
# Hard 1 — Animal Deception (complete)
# ─────────────────────────────────────────────
ANIMAL_DECEPTION = {
    "id":           "animal_deception",
    "title":        "Animal Deception and Game Theory",
    "difficulty":   "advanced",
    "duration_sec": 70,
    "keywords":     ["deception", "frogs", "evolution", "game theory", "biology"],
    "audio_path":   "audio/hard1.mp3",
    "segments": [
        _seg(0,
            "Hi, Professor Anderson. That was a really interesting lecture in class today.",
            0.0, 5.0,
            [_w("Hi,",_stress()),_w("Professor",_stress()),_w("Anderson.",_nuclear(),_fall()),
             _w("That",_stress()),_w("was",_weak("/wəz/")),_w("a",_weak("/ə/")),
             _w("really",_stress()),_w("interesting",_stress()),_w("lecture",_stress()),
             _w("in",_weak("/ɪn/")),_w("class",_stress()),_w("today",_nuclear(),_fall())],
            "'was', 'a', 'in' reduce. Two tone units — greeting then comment.",
            "was、a、in 弱化。两个语调单位：打招呼，然后评论。",
            intonation="fall",
            pauses=[3],
        ),
        _seg(1,
            "Animals' use of deception, ways they play tricks on other animals, that's a fascinating area, one we're really just starting to understand.",
            5.0, 14.0,
            [_w("Animals'",_stress()),_w("use",_stress()),_w("of",_weak("/əv/")),
             _w("deception,",_nuclear(),_rise()),_w("ways",_stress()),_w("they",_weak("/ðə/")),
             _w("play",_stress()),_w("tricks",_stress()),_w("on",_weak("/ɒn/")),
             _w("other",_stress()),_w("animals,",_nuclear(),_rise()),_w("that's",_stress()),
             _w("a",_weak("/ə/")),_w("fascinating",_stress()),_w("area,",_nuclear(),_rise()),
             _w("one",_stress()),_w("we're",_weak("/wɪə/")),_w("really",_stress()),
             _w("just",_stress()),_w("starting",_link("linking →")),
             _w("to",_link("← to"),_weak("/tə/")),_w("understand",_nuclear(),_fall())],
            "Three appositional rises. Final fall 'understand'. 'starting to' links.",
            "三个同位短语各有升调。understand 处最终降调。starting to 连读。",
            intonation="fall",
            pauses=[3, 10, 14],
        ),
        _seg(2,
            "You know, selective adaptations over time are one thing, like non-poisonous butterflies that have come to look like poisonous ones.",
            14.0, 22.0,
            [_w("You",_weak("/jə/")),_w("know,",_fall_rise()),_w("selective",_stress()),
             _w("adaptations",_stress()),_w("over",_stress()),_w("time",_stress()),
             _w("are",_weak("/ə/")),_w("one",_stress()),_w("thing,",_nuclear(),_rise()),
             _w("like",_stress()),_w("non-poisonous",_stress()),_w("butterflies",_stress()),
             _w("that",_weak("/ðət/")),_w("have",_weak("/əv/")),_w("come",_stress()),
             _w("to",_weak("/tə/")),_w("look",_link("linking →")),
             _w("like",_link("← like"),_stress()),_w("poisonous",_stress()),
             _w("ones",_nuclear(),_fall())],
            "'You know' — fall-rise. Rise on 'thing' — contrast coming. 'look like' links.",
            "You know 使用 fall-rise。thing 处升调（后面有对比）。look like 连读。",
            intonation="fall",
            pauses=[1, 8],
        ),
        _seg(3,
            "But the idea that animals of the same species intentionally deceive each other — I'd never heard that before.",
            22.0, 29.0,
            [_w("But",_stress()),_w("the",_weak("/ðə/")),_w("idea",_stress()),
             _w("that",_weak("/ðət/")),_w("animals",_stress()),_w("of",_weak("/əv/")),
             _w("the",_weak("/ðə/")),_w("same",_stress()),_w("species",_stress()),
             _w("intentionally",_stress()),_w("deceive",_stress()),
             _w("each",_link("linking →")),_w("other",_nuclear(),_rise()),
             _w("I'd",_stress()),_w("never",_stress()),_w("heard",_stress()),
             _w("that",_stress()),_w("before",_nuclear(),_fall())],
            "Long subject clause — rise on 'other', suspense. Strong fall 'before'. 'each other' links.",
            "长主语从句在 other 处升调（制造悬念）。before 处强烈降调（惊讶）。each other 连读。",
            intonation="fall",
            pauses=[12],
        ),
        _seg(4,
            "Right. Like, there are male frogs who lower their voices and end up sounding bigger than they really are.",
            29.0, 37.0,
            [_w("Right.",_stress(),_fall()),_w("Like,",_fall_rise()),
             _w("there",_weak("/ðə/")),_w("are",_weak("/ə/")),_w("male",_stress()),
             _w("frogs",_stress()),_w("who",_weak("/hʊ/")),_w("lower",_stress()),
             _w("their",_weak("/ðə/")),_w("voices",_stress()),_w("and",_weak("/ən/")),
             _w("end",_link("linking →")),_w("up",_link("← up"),_stress()),
             _w("sounding",_stress()),_w("bigger",_stress()),_w("than",_weak("/ðən/")),
             _w("they",_weak("/ðə/")),_w("really",_stress()),_w("are",_nuclear(),_fall())],
            "'Like' — fall-rise, introducing example. 'There are' both reduce. 'end up' links.",
            "Like 使用 fall-rise（引入例子）。There are 都弱化。end up 连读。",
            intonation="fall",
            pauses=[1],
        ),
        _seg(5,
            "So they do that to keep other frogs from invading their territory.",
            37.0, 42.0,
            [_w("So",_stress()),_w("they",_weak("/ðə/")),_w("do",_stress()),
             _w("that",_weak("/ðət/")),_w("to",_weak("/tə/")),_w("keep",_stress()),
             _w("other",_stress()),_w("frogs",_stress()),_w("from",_weak("/frəm/")),
             _w("invading",_stress()),_w("their",_weak("/ðə/")),
             _w("territory",_nuclear(),_fall())],
            "'do' — emphatic, checking understanding. 'that', 'to', 'their' reduce.",
            "do 是强调（确认理解）。that、to、their 弱化。",
            intonation="fall",
        ),
        _seg(6,
            "Bigger frogs have deeper voices, so if a smaller frog can imitate that deep voice, well...",
            42.0, 49.0,
            [_w("Bigger",_stress()),_w("frogs",_stress()),_w("have",_stress()),
             _w("deeper",_stress()),_w("voices,",_nuclear(),_rise()),_w("so",_stress()),
             _w("if",_weak("/ɪf/")),_w("a",_weak("/ə/")),_w("smaller",_stress()),
             _w("frog",_stress()),_w("can",_weak("/kən/")),_w("imitate",_stress()),
             _w("that",_weak("/ðət/")),_w("deep",_stress()),_w("voice,",_nuclear(),_rise()),
             _w("well",_fall_rise())],
            "Rise 'voices' — conditional. Rise 'voice' — implication open. 'well' — fall-rise.",
            "voices 升调（有条件从句）。voice 升调（含义开放）。well 使用 fall-rise。",
            intonation="fall_rise",
            pauses=[4, 14],
        ),
        _seg(7,
            "Yeah, I can see how that might do the trick.",
            49.0, 53.0,
            [_w("Yeah,",_fall_rise()),_w("I",_weak("/aɪ/")),_w("can",_weak("/kən/")),
             _w("see",_stress()),_w("how",_stress()),_w("that",_weak("/ðət/")),
             _w("might",_stress()),_w("do",_stress()),_w("the",_weak("/ðə/")),
             _w("trick",_nuclear(),_fall())],
            "'Yeah' — fall-rise, acknowledgement. 'can', 'that', 'the' reduce.",
            "Yeah 使用 fall-rise（认同）。can、that、the 弱化。",
            intonation="fall",
        ),
        _seg(8,
            "But anyway, what I wanted to ask was, when you started talking about game theory, well, I know a little bit about it, but I'm not clear about its use in biology.",
            53.0, 63.0,
            [_w("But",_stress()),_w("anyway,",_fall_rise()),_w("what",_stress()),
             _w("I",_weak("/aɪ/")),_w("wanted",_stress()),_w("to",_weak("/tə/")),
             _w("ask",_stress()),_w("was,",_nuclear(),_rise()),_w("when",_weak("/wən/")),
             _w("you",_weak("/jə/")),_w("started",_stress()),_w("talking",_link("linking →")),
             _w("about",_link("← about"),_stress()),_w("game",_stress()),
             _w("theory,",_nuclear(),_rise()),_w("well,",_fall_rise()),
             _w("I",_weak("/aɪ/")),_w("know",_stress()),_w("a",_weak("/ə/")),
             _w("little",_stress()),_w("bit",_stress()),_w("about",_stress()),
             _w("it,",_nuclear(),_rise()),_w("but",_stress()),_w("I'm",_weak("/aɪm/")),
             _w("not",_stress()),_w("clear",_stress()),_w("about",_stress()),
             _w("its",_weak("/ɪts/")),_w("use",_stress()),_w("in",_weak("/ɪn/")),
             _w("biology",_nuclear(),_fall())],
            "Long build-up with multiple rises. 'talking about' links. 'well' — fall-rise mid-sentence.",
            "长铺垫，多处升调。talking about 连读。well 使用 fall-rise（话语标记）。",
            intonation="fall",
            pauses=[7, 14, 21],
        ),
        _seg(9,
            "Yeah, it's fairly new to biology. Basically, it uses math to predict what an individual will do under certain circumstances.",
            63.0, 72.0,
            [_w("Yeah,",_fall_rise()),_w("it's",_weak("/ɪts/")),_w("fairly",_stress()),
             _w("new",_stress()),_w("to",_weak("/tə/")),_w("biology.",_nuclear(),_fall()),
             _w("Basically,",_stress(),_fall_rise()),_w("it",_weak("/ɪt/")),
             _w("uses",_stress()),_w("math",_stress()),_w("to",_weak("/tə/")),
             _w("predict",_stress()),_w("what",_stress()),_w("an",_link("linking →")),
             _w("individual",_link("← individual"),_stress()),_w("will",_weak("/wɪl/")),
             _w("do",_stress()),_w("under",_stress()),_w("certain",_stress()),
             _w("circumstances",_nuclear(),_fall())],
            "'Yeah' — fall-rise. 'Basically' — fall-rise, signals definition. 'an individual' links.",
            "Yeah 使用 fall-rise。Basically 使用 fall-rise（要下定义了）。an individual 连读。",
            intonation="fall",
            pauses=[5],
        ),
        _seg(10,
            "For example, a business sells computers, and they want to sell their computers to a big university. But there's another company bidding, too. So, what should they do?",
            72.0, 82.0,
            [_w("For",_weak("/fə/")),_w("example,",_stress(),_fall_rise()),
             _w("a",_weak("/ə/")),_w("business",_stress()),_w("sells",_stress()),
             _w("computers,",_nuclear(),_rise()),_w("and",_weak("/ən/")),
             _w("they",_weak("/ðə/")),_w("want",_stress()),_w("to",_weak("/tə/")),
             _w("sell",_stress()),_w("their",_weak("/ðə/")),_w("computers",_stress()),
             _w("to",_weak("/tə/")),_w("a",_weak("/ə/")),_w("big",_stress()),
             _w("university.",_nuclear(),_fall()),_w("But",_stress()),
             _w("there's",_weak("/ðəz/")),_w("another",_stress()),_w("company",_stress()),
             _w("bidding,",_nuclear(),_rise()),_w("too.",_nuclear(),_fall()),
             _w("So,",_stress()),_w("what",_stress()),_w("should",_weak("/ʃəd/")),
             _w("they",_weak("/ðə/")),_w("do",_nuclear(),_rise())],
            "'For example' — fall-rise. Question ends with rise on 'do'. Short punchy sentences.",
            "For example 使用 fall-rise。do 处升调（提问）。短句节奏明快。",
            intonation="rise",
            pauses=[1, 5, 15, 22],
        ),
        _seg(11,
            "Well, try to offer the lowest price so they can compete, but still make money.",
            82.0, 88.0,
            [_w("Well,",_fall_rise()),_w("try",_stress()),_w("to",_weak("/tə/")),
             _w("offer",_link("linking →")),_w("the",_link("← the"),_weak("/ðə/")),
             _w("lowest",_stress()),_w("price",_nuclear(),_rise()),_w("so",_weak("/sə/")),
             _w("they",_weak("/ðə/")),_w("can",_weak("/kən/")),_w("compete,",_nuclear(),_rise()),
             _w("but",_stress()),_w("still",_stress()),_w("make",_stress()),
             _w("money",_nuclear(),_fall())],
            "'Well' — fall-rise, tentative answer. 'offer the' links. Two rises before final fall.",
            "Well 使用 fall-rise（试探性回答）。offer the 连读。两处升调后最终降调。",
            intonation="fall",
            pauses=[6, 10],
        ),
    ],
}

# ─────────────────────────────────────────────
# Hard 2 — Organic Food (complete)
# ─────────────────────────────────────────────
ORGANIC_FOOD = {
    "id":           "organic_food",
    "title":        "The Cafeteria's Food Policy",
    "difficulty":   "advanced",
    "duration_sec": 75,
    "keywords":     ["cafeteria", "organic", "healthy", "fried food", "food policy"],
    "audio_path":   "audio/hard2.mp3",
    "segments": [
        _seg(0,
            "Hi, I'm sorry to interrupt. Could I ask you a few questions?",
            0.0, 5.0,
            [_w("Hi,",_stress()),_w("I'm",_weak("/aɪm/")),_w("sorry",_stress()),
             _w("to",_weak("/tə/")),_w("interrupt.",_nuclear(),_fall()),
             _w("Could",_weak("/kəd/")),_w("I",_weak("/aɪ/")),_w("ask",_stress()),
             _w("you",_weak("/jə/")),_w("a",_weak("/ə/")),_w("few",_stress()),
             _w("questions",_nuclear(),_rise())],
            "Rise on 'questions' — polite request. 'Could', 'I', 'you', 'a' reduce.",
            "questions 处升调（礼貌请求）。Could、I、you、a 全部弱化。",
            intonation="rise",
            pauses=[3],
        ),
        _seg(1,
            "Sure, but if it's about your meal plan, you'll need to go to room 45 just down the hall.",
            5.0, 11.0,
            [_w("Sure,",_stress(),_fall_rise()),_w("but",_stress()),_w("if",_weak("/ɪf/")),
             _w("it's",_weak("/ɪts/")),_w("about",_stress()),_w("your",_weak("/jə/")),
             _w("meal",_stress()),_w("plan,",_nuclear(),_rise()),_w("you'll",_weak("/jʊl/")),
             _w("need",_stress()),_w("to",_weak("/tə/")),_w("go",_stress()),
             _w("to",_weak("/tə/")),_w("room",_stress()),_w("45",_nuclear()),
             _w("just",_stress()),_w("down",_stress()),_w("the",_weak("/ðə/")),
             _w("hall",_nuclear(),_fall())],
            "'Sure' — fall-rise, willing but with condition. Rise 'plan'. 'you'll', 'if' reduce.",
            "Sure 使用 fall-rise（愿意但有条件）。plan 处升调（条件从句）。you'll、if 弱化。",
            intonation="fall",
            pauses=[0, 7],
        ),
        _seg(2,
            "No, I'm okay with my meal plan. I'm actually here about the food in the student cafeteria.",
            11.0, 18.0,
            [_w("No,",_stress(),_fall()),_w("I'm",_weak("/aɪm/")),_w("okay",_stress()),
             _w("with",_weak("/wɪ/")),_w("my",_weak("/mɪ/")),_w("meal",_stress()),
             _w("plan.",_nuclear(),_fall()),_w("I'm",_weak("/aɪm/")),
             _w("actually",_stress()),_w("here",_stress()),_w("about",_stress()),
             _w("the",_weak("/ðə/")),_w("food",_stress()),_w("in",_weak("/ɪn/")),
             _w("the",_weak("/ðə/")),_w("student",_stress()),
             _w("cafeteria",_nuclear(),_fall())],
            "'No' — own fall, contrast marker. 'actually' signals the real topic.",
            "No 独立降调（转折）。actually 引出真正话题。",
            intonation="fall",
            pauses=[5],
        ),
        _seg(3,
            "Oh, we do feed a lot of students, so we can't always honor individual requests. I'm sure you understand.",
            18.0, 26.0,
            [_w("Oh,",_fall_rise()),_w("we",_weak("/wɪ/")),_w("do",_stress()),
             _w("feed",_stress()),_w("a",_weak("/ə/")),_w("lot",_stress()),
             _w("of",_weak("/əv/")),_w("students,",_nuclear(),_rise()),
             _w("so",_weak("/sə/")),_w("we",_weak("/wɪ/")),_w("can't",_stress()),
             _w("always",_stress()),_w("honor",_link("linking →")),
             _w("individual",_link("← individual"),_stress()),
             _w("requests.",_nuclear(),_fall()),_w("I'm",_weak("/aɪm/")),
             _w("sure",_stress()),_w("you",_weak("/jə/")),_w("understand",_nuclear(),_fall())],
            "'Oh' — fall-rise, mild deflection. 'do' — emphatic. 'honor individual' links.",
            "Oh 使用 fall-rise（轻微转移）。do 是对比强调。honor individual 连读。",
            intonation="fall",
            pauses=[7, 14],
        ),
        _seg(4,
            "It's just that I'm a little concerned — I mean, a lot of us are — that a lot of the food you serve isn't really that healthy.",
            26.0, 35.0,
            [_w("It's",_weak("/ɪts/")),_w("just",_stress()),_w("that",_weak("/ðət/")),
             _w("I'm",_weak("/aɪm/")),_w("a",_weak("/ə/")),_w("little",_stress()),
             _w("concerned,",_nuclear(),_rise()),_w("I",_stress()),_w("mean,",_fall_rise()),
             _w("a",_weak("/ə/")),_w("lot",_stress()),_w("of",_weak("/əv/")),
             _w("us",_weak("/əs/")),_w("are,",_nuclear(),_rise()),_w("that",_weak("/ðət/")),
             _w("a",_weak("/ə/")),_w("lot",_stress()),_w("of",_weak("/əv/")),
             _w("the",_weak("/ðə/")),_w("food",_stress()),_w("you",_weak("/jə/")),
             _w("serve",_stress()),_w("isn't",_stress()),_w("really",_stress()),
             _w("that",_weak("/ðət/")),_w("healthy",_nuclear(),_fall())],
            "Parenthetical insertion with rise. 'It's just that' — softener. Complex intonation.",
            "插入语有升调。It's just that 是缓和开场。嵌套语调结构复杂。",
            intonation="fall",
            pauses=[6, 13],
        ),
        _seg(5,
            "As a matter of fact, we recently changed the type of oil we use in our fryer. It's the healthiest available.",
            35.0, 43.0,
            [_w("As",_weak("/əz/")),_w("a",_weak("/ə/")),_w("matter",_stress()),
             _w("of",_weak("/əv/")),_w("fact,",_nuclear(),_rise()),_w("we",_weak("/wɪ/")),
             _w("recently",_stress()),_w("changed",_stress()),_w("the",_weak("/ðə/")),
             _w("type",_stress()),_w("of",_weak("/əv/")),_w("oil",_stress()),
             _w("we",_weak("/wɪ/")),_w("use",_stress()),_w("in",_weak("/ɪn/")),
             _w("our",_weak("/ə/")),_w("fryer.",_nuclear(),_fall()),_w("It's",_weak("/ɪts/")),
             _w("the",_weak("/ðə/")),_w("healthiest",_nuclear()),_w("available",_fall())],
            "'As a matter of fact' — heavily reduced discourse marker. Short punchy sentence at end.",
            "As a matter of fact 是话语标记，大量弱化。最后一句短促有力。",
            intonation="fall",
            pauses=[4, 16],
        ),
        _seg(6,
            "Well, I try not to eat too many fried foods anyway. I'm just aware that... you see, I used to work in a natural food store, and they had all this literature advising people to eat fresh, organically grown food.",
            43.0, 56.0,
            [_w("Well,",_fall_rise()),_w("I",_weak("/aɪ/")),_w("try",_stress()),
             _w("not",_stress()),_w("to",_weak("/tə/")),_w("eat",_link("linking →")),
             _w("too",_link("← too"),_stress()),_w("many",_stress()),_w("fried",_stress()),
             _w("foods",_stress()),_w("anyway.",_nuclear(),_fall()),
             _w("I'm",_weak("/aɪm/")),_w("just",_stress()),_w("aware",_stress()),
             _w("that...",_nuclear(),_rise()),_w("you",_weak("/jə/")),
             _w("see,",_fall_rise()),_w("I",_stress()),_w("used",_stress()),
             _w("to",_weak("/tə/")),_w("work",_link("linking →")),
             _w("in",_link("← in"),_weak("/ɪn/")),_w("a",_weak("/ə/")),
             _w("natural",_stress()),_w("food",_stress()),_w("store,",_nuclear(),_rise()),
             _w("and",_weak("/ən/")),_w("they",_weak("/ðə/")),_w("had",_stress()),
             _w("all",_stress()),_w("this",_stress()),_w("literature",_stress()),
             _w("advising",_stress()),_w("people",_stress()),_w("to",_weak("/tə/")),
             _w("eat",_link("linking →")),_w("fresh,",_nuclear(),_rise()),
             _w("organically",_stress()),_w("grown",_stress()),_w("food",_nuclear(),_fall())],
            "'Well' — fall-rise. 'eat too' links. 'you see' — fall-rise. 'used to' → /juːstə/. 'work in' links.",
            "Well 使用 fall-rise。eat too 连读。you see 使用 fall-rise。used to 读成 /juːstə/。work in 连读。",
            intonation="fall",
            pauses=[10, 14, 23, 32],
        ),
        _seg(7,
            "Working there really opened my eyes.",
            56.0, 59.5,
            [_w("Working",_stress()),_w("there",_stress()),_w("really",_stress()),
             _w("opened",_link("linking →")),_w("my",_link("← my"),_weak("/mɪ/")),
             _w("eyes",_nuclear(),_fall())],
            "'opened my' links. Strong stresses — emphatic conclusion.",
            "opened my 连读。连续强重音——强调性结语。",
            intonation="fall",
        ),
        _seg(8,
            "We served only certified organic food, most of which was from local farms. It's not something we can afford to do on a daily basis, and there aren't too many organic farms around here.",
            59.5, 71.0,
            [_w("We",_weak("/wɪ/")),_w("served",_stress()),_w("only",_stress()),
             _w("certified",_stress()),_w("organic",_stress()),_w("food,",_nuclear(),_rise()),
             _w("most",_stress()),_w("of",_weak("/əv/")),_w("which",_stress()),
             _w("was",_weak("/wəz/")),_w("from",_weak("/frəm/")),_w("local",_stress()),
             _w("farms.",_nuclear(),_fall()),_w("It's",_weak("/ɪts/")),_w("not",_stress()),
             _w("something",_stress()),_w("we",_weak("/wɪ/")),_w("can",_weak("/kən/")),
             _w("afford",_stress()),_w("to",_weak("/tə/")),_w("do",_stress()),
             _w("on",_weak("/ɒn/")),_w("a",_weak("/ə/")),_w("daily",_stress()),
             _w("basis,",_nuclear(),_rise()),_w("and",_weak("/ən/")),
             _w("there",_weak("/ðə/")),_w("aren't",_stress()),_w("too",_stress()),
             _w("many",_stress()),_w("organic",_stress()),_w("farms",_stress()),
             _w("around",_link("linking →")),_w("here",_nuclear(),_fall())],
            "Rise 'food' — relative clause coming. 'most of which' reduces. 'around here' links.",
            "food 处升调（后有关系从句）。most of which 弱化。around here 连读。",
            intonation="fall",
            pauses=[5, 12, 24],
        ),
        _seg(9,
            "But sometimes the produce we offer is organically grown. It depends on the season and the prices, of course. That's good to know.",
            71.0, 81.0,
            [_w("But",_stress()),_w("sometimes",_stress()),_w("the",_weak("/ðə/")),
             _w("produce",_stress()),_w("we",_weak("/wɪ/")),_w("offer",_link("linking →")),
             _w("is",_link("← is"),_weak("/ɪz/")),_w("organically",_stress()),
             _w("grown.",_nuclear(),_fall()),_w("It",_weak("/ɪt/")),_w("depends",_stress()),
             _w("on",_weak("/ɒn/")),_w("the",_weak("/ðə/")),_w("season",_stress()),
             _w("and",_weak("/ən/")),_w("the",_weak("/ðə/")),_w("prices,",_nuclear(),_rise()),
             _w("of",_weak("/əv/")),_w("course.",_nuclear(),_fall()),
             _w("That's",_stress()),_w("good",_stress()),_w("to",_weak("/tə/")),
             _w("know",_nuclear(),_fall())],
            "'offer is' links. Rise 'prices' — more factors. 'of course' — tail phrase. Short conclusions.",
            "offer is 连读。prices 升调（还有其他因素）。of course 是尾语降调。结尾短句有力。",
            intonation="fall",
            pauses=[8, 16],
        ),
    ],
}


MATERIALS = {m["id"]: m for m in [
    MUSIC_PRODIGY,
    LANGUAGE_LAB,
    LIBRARY,
    CHOIR_NOISE,
    JAZZ_BAND,
    ANIMAL_DECEPTION,
    ORGANIC_FOOD,
]}

def get_material(material_id):   return MATERIALS[material_id]
def get_all_materials():         return list(MATERIALS.values())
def get_segments(material):      return material["segments"]
